### ISSUE TITLE
How to pronounce symbolic operators?

### ISSUE THREAD

**Issue by DaniRey** [fommil/fpmortals#1]
When I read code, I always read it out loud in my head. To do so, I need to know how to pronounce operators. 

I read 
 val a = "abc"
as 
 a is "abc"
others would read it as 
 assign "abc" to a

With all the symbolic operators in Scalaz I struggle, because I do not know how to pronounce them.

In the chapter "## Incomprehensible" you give a hint.

A> `|>` is often called the *thrush operator* because of its uncanny resemblance to
A> the cute bird. Those who do not like symbolic operators can use the alias
A> `.into`.

It would help me a lot to know how to pronounce all those operators. Or how to read this code.

Is
`a <- getA       |> liftFutureOption` 

  getA into liftFutureOption
or 
  lift getA into FutureOption

**Comment by fommil** [comment]
For the cases where the `@op` is used, a symbolic operator should always be beside a named method, which is the pronunciation, if you want it. But a lot of the time people use silly names, there is no convention. I don't think I can do any more on this front other that point this out.

**Comment by DaniRey** [comment]
I think this is a topic, where we struggle as an industry. See Felienne Hermans' blog 
http://www.felienne.com/archives/5947 and paper in case I sparked your interest.
I would appreciate, if you could point this out and add the name of the method to which the @op belongs to the boxes which contain the names of the operators, i.e. tie fighter.

**Comment by fommil** [comment]
Yup, I've added a piece of text about this.

**Comment by fommil** [comment]
```
When there is a custom symbolic =@op=, it can be pronounced like its method
name. e.g. =<= is pronounced "less than", not "left angle bracket".

```

**Comment by DaniRey** [comment]
Perfect
