### ISSUE TITLE
Explain contramap in detail

### ISSUE THREAD

**Issue by DaniRey** [fommil/fpmortals#11]
In the chapter "Divide and Conquer",  I read the part about contramap multiple times and I still don't understand it. As far as I understand `Divisible[Equal].conquer[String]` provides and implementation of Equal for String, which always returns true. But I can't follow the implementation of `contramap`.

**Comment by fommil** [comment]
I'm just going to remove a lot of the map/contramap/divide/apply/fromIso stuff from this chapter and return to it in the Typeclass Derivation chapter. Actually `conquer[String]` is a typo, it should be `conquer[Nil.type]` or some other thing that is either an `object` or zero param `case class`.
