### ISSUE TITLE
show usage of echo method with TerminalSync?

### ISSUE THREAD

**Issue by philipschwarz** [fommil/fpmortals#13]
Hello Sam,

I just started reading your book and have not used scalaz before.

Can I suggest that at the end of '1.1 Abstracting over Execution', you show the reader how to use the echo method with TerminalSync (and maybe with TerminalAsync, too).

What do I have to do to achieve that?

I got started having a go, but I am now stuck.

I pasted the code from 1.1 into a Scala file.
I gave TerminalSync's read and write methods an implementation.
I wrote a main method that just calls echo.
Now I need an implicit terminal and an implicit execution. How do I do that?

I defined implicit val aTerminal = TerminalSync, and that seems to work.

How do I get an implicit Execution?

![image](https://user-images.githubusercontent.com/116804/30248106-a1897684-9619-11e7-8b5f-5f8f40c7b49e.png)

Also, I get these compilation errors:

![image](https://user-images.githubusercontent.com/116804/30248121-d51a753e-9619-11e7-8310-de79856c6e1a.png)

Here is the code: https://gist.github.com/philipschwarz/0e46c2567c2d8a532539e1d39c1bb4f7

Thanks in advance for your help.

Philip

**Comment by fommil** [comment]
Oh, you may need to call it as `echo[Now]`

You can make both objects implicit... but there is a section later on about why implicit val is better.

**Comment by fommil** [comment]
Remove the object Execution, leave the Ops visible.

Yeah, I'll maybe put a full working version in this repo for people. A goal of the book is that it is a reading book, not an exercise book, but obviously people will want to follow along and I should make that easier.

**Comment by philipschwarz** [comment]
Removing the Execution object and leaving the Ops visible eliminates the compilation errors (also had to use scala.io.StdIn.readLine rather than deprecated scala.Predef.readLine) 

https://gist.github.com/philipschwarz/58afd88408ee576e26e1cb529f799f33

But how do I get an implicit Execution[Now] ?

![image](https://user-images.githubusercontent.com/116804/30250234-85b3a992-9642-11e7-9733-92b37fa3f847.png)

FWIW, this seems to work:

![image](https://user-images.githubusercontent.com/116804/30250248-c5022ccc-9642-11e7-836d-b8c2bcbf95da.png)

https://gist.github.com/philipschwarz/0d5edd174056c8c121537b99655d794f

![image](https://user-images.githubusercontent.com/116804/30250257-fd9ec2a2-9642-11e7-9bb7-8a7dd2565d61.png)

**Comment by fommil** [comment]
Looks like you got it :-)

**Comment by philipschwarz** [comment]
Got the Future version to work too:

![image](https://user-images.githubusercontent.com/116804/30250995-9287b232-964f-11e7-84a6-ebad917184f5.png)

![image](https://user-images.githubusercontent.com/116804/30251025-ebc99662-964f-11e7-8bc2-a6bf9c22a7ce.png)

**Comment by philipschwarz** [comment]
What makes use of the Ops implicit?

**Comment by fommil** [comment]
the `for` comprehensions... it will become more obvious when you read the next chapter :smile:

btw, if you'd like to send this code in a PR to `src/main/scala/chapter1.scala` of this repo, I'd be happy to accept it.

**Comment by fommil** [comment]
Incidentally, you can use the book's version of the `Ops` by doing an

```scala
import Execution._
```

I was just suggesting something quick that I could send from my phone.

**Comment by fommil** [comment]
actually, never mind, I'm going to push this code to the repo and refer to it from the text. Thanks for flagging this up. I'll help with the other code snippets so we can do similar there.

**Comment by philipschwarz** [comment]
ok, I was literally just reading your latest comments - btw I don't think I can see any code in https://github.com/fommil/fpmortals. Where is src/main/scala/chapter1.scala?

**Comment by fommil** [comment]
https://github.com/fommil/fpmortals/blob/master/src/main/scala/chapter1.scala
