### ISSUE TITLE
Misleading sentence with by name and lazy

### ISSUE THREAD

**Issue by zainab-ali** [fommil/fpmortals#14]
The section on _Data and Functionality, Generalised ADTs_ contains the following sentence:

> A similar caveat applies to by name, known as lazy parameters

There's a key difference between **by name** and **lazy** parameters, as pointed out [here](https://tpolecat.github.io/2014/06/26/call-by-name.html).

Maybe we should change this to just:
> A similar caveat applies to by name parameters

**Comment by fommil** [comment]
yup, well spotted.
