### ISSUE TITLE
A word about monad laws?

### ISSUE THREAD

**Issue by mgttlinger** [fommil/fpmortals#15]
Relatively early you write:

> Our Execution has the same signature as a trait in scalaz called Monad, except doAndThen is flatMap and create is pure. We say that C is monadic when there is an implicit Monad[C] available.

Do you think it would make sense to state here that the signature alone doesn't make a monad but it also has to behave in a certain way? (Stating and explaining them at that point in the book is certainly too soon)

In the category theory context those laws follow directly from the definition/signature, but in Scala that isn't necessarily the case.

**Comment by fommil** [comment]
hmm, I think I'll pass on this one... I don't want to get too deep at the beginning. There is plenty of rigour around Monads later on.
