### ISSUE TITLE
Never call `Some` directly unless you know what you pass is not `null`

### ISSUE THREAD

**Issue by mgttlinger** [fommil/fpmortals#17]
In the part about monad transformers you write:

> It is messy again, but it’s better than writing nested flatMap and map by hand. We can clean it up with a DSL that handles all the required conversions into OptionT[Future, _]
>
> def liftFutureOption[A](f: Future[Option[A]]) = OptionT(f)
> def liftFuture[A](f: Future[A]) = f.liftM[OptionT]
> def liftOption[A](o: Option[A]) = OptionT(o.pure[Future])
> def lift[A](a: A)               = liftOption(Some(a))

Here you can't be sure that `a` is not `null` so it would be better to call `Option` here. (`pure` wouldn't work in this case because that has to call `Some` directly for the monad to be lawfull)

**Comment by fommil** [comment]
good point, I'll update that. Although I think generally in the book we're assuming that things should not be `null`.
