### ISSUE TITLE
Italian Translation

### ISSUE THREAD

**Issue by fommil** [fommil/fpmortals#18]
@danieletorelli has shown interest.

- [x] fork this repo
- [x] delete the book.org file
- [ ] start converting the .md files (you can split them up however you find easiest)
- [ ] use graphviz to regenerate images (get the ground truth from the upstream `book.org`)
- [ ] localise the cover image using GIMP. The author field could read "by Sam Halliday, translated by **your name here**".
- [ ] when you have a first chapter ready, I will create a book at http://leanpub.com/fpmortals-it
- [ ] watch the upstream repository for bugfixes and new chapters (I am only planning one more chapter)
- [ ] use http://lulu.com to create physical prints from leanpub's "export" option.

I would request that the minimum price of the final book to be $0, but you can use what you want. I used $25 minimum when writing the book, and set it to $0 when I was finished.
you can create a custom cover too. I don't need any royalties.

**Comment by danieletorelli** [comment]
@fommil repository is here: https://github.com/danieletorelli/fpmortals-it

You can mark step 1 and 2 as done.

**Comment by fommil** [comment]
@danieletorelli how is the progress? :smile:
