### ISSUE TITLE
Footnote reference explaining the name of the thrush operator?

### ISSUE THREAD

**Issue by mgttlinger** [fommil/fpmortals#18]
When you mention the thrush operator:

> combined with the thrush operator |>, which applies the function on the right to the value on the left, to visually separate the logic from the transformers

Do you think it would be good to put a footnote reference to [the book](https://en.wikipedia.org/wiki/To_Mock_a_Mockingbird) where the name is taken from, because when I was learning that stuff I wondered where that name came from.

**Comment by fommil** [comment]
heh, I didn't know that, thanks :smile: why is it named after the bird in the book and not just the bird?

**Comment by mgttlinger** [comment]
The books assigns (mostly) bird names to combinators in combinatory logic and the thrush combinator happens to be the one we know and love.

**Comment by mgttlinger** [comment]
See: http://www.angelfire.com/tx4/cus/combinator/birds.html

**Comment by fommil** [comment]
I fear the full explanation may be quite a digression, but I'll add something...

**Comment by fommil** [comment]
ok, your suggestions should be live in a moment. Thanks!
