### ISSUE TITLE
Spanish Translation

### ISSUE THREAD

**Issue by fommil** [fommil/fpmortals#19]
@insdami, @diesalbla and @osocron have expressed interest

- [x] fork this repo
- [x] delete the book.org file
- [x] start converting the .md files (you can split them up however you find easiest)
- [ ] use graphviz to regenerate images (get the ground truth from the upstream `book.org`)
- [ ] localise the cover image using GIMP. The author field could read "by Sam Halliday, translated by **your name here**".
- [x] when you have a first chapter ready, I will create a book at http://leanpub.com/fpmortals-es
- [ ] watch the upstream repository for bugfixes and new chapters (I am only planning one more chapter)
- [ ] use http://lulu.com to create physical prints from leanpub's "export" option.

I would request that the minimum price of the final book to be $0, but you can use what you want. I used $25 minimum when writing the book, and set it to $0 when I was finished.
you can create a custom cover too. I don't need any royalties.

**Comment by oscarvarto** [comment]
I will do it.

**Comment by fommil** [comment]
@oscarvarto please create an account at leanpub.com and let me know your username and the title of the book.

**Comment by fommil** [comment]
@oscarvarto just the title is enough, but you now have permissions to edit :smile: https://leanpub.com/fpmortals-es :tada:

**Comment by oscarvarto** [comment]
Hi @fommil 

I must say that I am loving the Free Software experience so far. But I want to learn more. We need to talk :)

Front matter done!

**Comment by fommil** [comment]
@oscarvarto how is the progress? :smile:

**Comment by oscarvarto** [comment]
@fommil This week I wrote this:

https://leanpub.com/fpmortals-es/read#leanpub-auto-tipos-de-datos-de-scalaz

I couldn't work on translation stuff last holiday season, but I like to finish the things I start. Hopefully I will finish the complete book in a few months.
It also depends on my current circumstances.

Have a great day @fommil

**Comment by oscarvarto** [comment]
Translation is complete.

**Comment by fommil** [comment]
@oscarvarto that is amazing, I'll tweet this out, thank you so much! Can you please update the parts of the text that are out of date from bugfixes in the English version? Also please let me know if you found any bugs (can we run a script over the diff of `<code>` fragments maybe?)
