### ISSUE TITLE
What you call `algebra` is actually an `object algebra interface`

### ISSUE THREAD

**Issue by mgttlinger** [fommil/fpmortals#19]
Confused about the meaning of the word `algebra` which you use regularly in your drone implementation example, I went digging through literature to find out in what way what you are implementing could be seen as an algebra.
Given that the "Finally Tagless" paper seemed to avoid calling those specifications algebras I finally (no pun intended) ended up at [this paper](http://www.lirmm.fr/~ducour/Doc-objets/ECOOP2012/ECOOP/ecoop/002.pdf) which describes what you are doing and (as far as I understad) introduced the name `object algebra` for the instances and `object algebra interface` for the signature specification which you call `algebra` as I understood.
I'm not sure if the word algebra helps in that chapter or rather will cause confusion later on when introducing the notion of **algebraic** data types (which is something you read regularly at places talking about FP).

**Comment by fommil** [comment]
"algebra" has started to mean the `trait` that defines the algebra in scala. I hit the name overload problem with the `algebraic` in ADTs and I just had an aside to say "not the same thing as trait algebras" and left it at that. Then I read it a few times and decided that it didn't really add anything and it felt like I was apologising for the names so I just explained *what* the algebra is and removed the apology.

**Comment by mgttlinger** [comment]
Is that a common notion anywhere? I've never seen a `trait` used like that being called an algebra.

**Comment by fommil** [comment]
yeah, the freestyle folks (and chatting to scalaz users) certainly call it that way. Although most of them would say "finally tagless style algebra" which I think is redundant. I plan on mentioning that in the Free Monad chapter.

I think the "interface" part of your reading is implicit with how `trait` is seen in scala and `object` is just such a loaded word... in fact using it would probably cause more confusion with the typical ex-java audience.

**Comment by mgttlinger** [comment]
It is an encoding of an algebra, but the encoding itself isn't an algebra, or at least not in a notion I am familiar with. My proposal would rather be to call this `trait` _API specification_ or something along those lines as this captures the intended purpose rather well, avoids the confusion with ADTs and is less fishy than just calling it `algebra`.

**Comment by fommil** [comment]
I'll have a think about it... but to the typical java dev a `trait` already *is* an interface (or specification). I don't want to diverge from the industrial nomenclature on key concepts like this.

**Comment by fommil** [comment]
I just noticed that the chapter is called "Interfaces / Algebras" :stuck_out_tongue:

**Comment by mgttlinger** [comment]
Yes but the interfaces part is not that dominant in the _naming things_ part of the chapter :wink:
