### ISSUE TITLE
Remain open about naming

### ISSUE THREAD

**Issue by DaniRey** [fommil/fpmortals#2]
At the start of "# Scalaz Typeclasses" you have the following.

> There has been criticism of the naming in scalaz, and functional
programming in general. Most names follow the conventions introduced
in the Haskell programming language, based on *Category Theory*. Feel
free to set up `type` aliases in your own codebase if you would prefer
to use verbs based on the primary functionality of the typeclass (e.g.
`Mappable`, `Pureable`, `FlatMappable`) until you are comfortable with
the standard names.

I suggest you remove "until you are comfortable with the standard names." With "Fell free to..." you let the reader choose what he prefers. Don't make him feel bad for his choice.

**Comment by fommil** [comment]
I reworded this slightly to

```
Feel free to set up =type= aliases if
verbs based on the primary functionality are easier to remember when learning
(e.g. =Mappable=, =Pureable=, =FlatMappable=).
```

**Comment by DaniRey** [comment]
Perfect
