### ISSUE TITLE
What role does the identity function play in the foldable explanation?

### ISSUE THREAD

**Issue by mgttlinger** [fommil/fpmortals#20]
In the explanation of `fold` you write:

> The simplest thing to do with Foldable is to use the identity function, the natural sum of the monoidal elements, giving us fold (and left/right variants to allow choosing specific performance criteria):

What has the identity function to do with getting `fold` here?

**Comment by fommil** [comment]
Looks like a typo

**Comment by fommil** [comment]
Ah, it should be foldMap not Foldable.
