### ISSUE TITLE
Bahasa Indonesia Translation

### ISSUE THREAD

**Issue by fommil** [fommil/fpmortals#20]
@ibnuda has expressed interest

- [x] fork this repo
- [x] delete the book.org file
- [x] start converting the .md files (you can split them up however you find easiest)
- [ ] use graphviz to regenerate images (get the ground truth from the upstream `book.org`)
- [ ] localise the cover image using GIMP. The author field could read "by Sam Halliday, translated by **your name here**".
- [x] when you have a first chapter ready, I will create a book at http://leanpub.com/fpmortals-id
- [x] watch the upstream repository for bugfixes and new chapters (I am only planning one more chapter)
- [ ] use http://lulu.com to create physical prints from leanpub's "export" option.

I would request that the minimum price of the final book to be $0, but you can use what you want. I used $25 minimum when writing the book, and set it to $0 when I was finished.
you can create a custom cover too. I don't need any royalties.

**Comment by ibnuda** [comment]
Mr. Halliday,

I've forked this repo and the next commit will contain `book.org` file deletions. Currently at the process of translating "Application Design" chapter.

**Comment by ibnuda** [comment]
I've translated it, but haven't deleted the original text. Something like the following:
```
Original paragrah.

Translated paragraph.
```
I do this because I'm still looking for an editor in case I mistranslate it.

So, to answer your question, not yet, Mr. Halliday.

**Comment by fommil** [comment]
just ping me here when you are ready. Which language code should I use? e.g. `-es` for Spanish, `-fr` for French.

**Comment by ibnuda** [comment]
Should be `id`, Mr. Halliday.

**Comment by fommil** [comment]
@ibnuda you can call me Sam :smile:

**Comment by ibnuda** [comment]
Hello, Sam.

I've completed the translation. But unfortunately, I forgot that you've updated `backmatter.md`.
Is it okay if I manually copy paste from your master-branch?

**Comment by fommil** [comment]
@ibnuda you've **finished**? wow.

Yes please check with `master` what updates have happened since you started. There have been some corrections.

**Comment by ibnuda** [comment]
Yes, but there are still a few terms that I can't find the translation. When I've finally translated those terms, I think the book can be published.

Okay, I will check the issues.

**Comment by ibnuda** [comment]
Hello, Sam.

Per [this commit](https://github.com/ibnuda/fpmortals/commit/874141c0897bd357b8bd2787a5faded5e699ddbe), I've finished the translation, including the Haskell addition in the `manuscript/backmatter.md`. So, if you deem the translation is ready, could you please create a page in the leanpub?

Also, what is the name of the fonts which you used in the `cover.xcf`?

Thanks.

**Comment by fommil** [comment]
You need to download https://sourcefoundry.org/hack/

**Comment by fommil** [comment]
@ibnuda what is the name of the book, and what is your email address? I have `iaji@siskam.link` but I'm not sure if that is correct.

**Comment by fommil** [comment]
"Pemrograman Fungsional untuk Rakyat Jelata dengan Scalaz" gets translated to "Functional Programming for Ugly People with Scalaz" :rofl:

**Comment by fommil** [comment]
@ibnuda https://leanpub.com/fpmortals-id it lives :smile: 

Once you sign up, I'll invite you as co-author and you can regenerate the files when you want (Publish). I can still see a lot of English.

**Comment by ibnuda** [comment]
Hello, Sam.

I've edited the cover and signed up to leanpub. My handle at that site is @ibnuda 

"rakyat jelata" is "common people" which i think almost an equal to "mortal" in this context.

And Thanks.
