### ISSUE TITLE
Functor variance is related to type parameter variance annotations

### ISSUE THREAD

**Issue by mgttlinger** [fommil/fpmortals#21]
When explaining the different functors you write:

> It is important to note that, although related at a theoretical level, the words covariant, contravariant and invariant do not directly refer to type variance (i.e. + and - prefixes that may be written in type signatures).

However those concepts are closely related. If you take as the functions in your `map`/`contramap` the _trivial_ conversions due to subtyping, then you get back the functions for the subtyping of the surrounding context.

See also [this post on the topic](https://typelevel.org/blog/2016/02/04/variance-and-functors.html)

**Comment by fommil** [comment]
Yes, this will be covered in the next chapter... but using the scalaz data type, not the Scala Language mechanism, for encoding variance. He blog you referenced is exactly the "theoretical level" I meant :-) I may add it as a hyperlink.

**Comment by fommil** [comment]
Hmm, maybe I'll find a different reference... cats seems to encourage the Scala Language +- variance (which is broken).

**Comment by fommil** [comment]
Btw what you describe is exactly widen and narrow, but scalaz doesn't have narrow.

**Comment by mgttlinger** [comment]
Then how about adding "but are related as we will see later"?

**Comment by fommil** [comment]
Yup, I'll do that.
