### ISSUE TITLE
Japanese Translation

### ISSUE THREAD

**Issue by fommil** [fommil/fpmortals#21]
Please comment here so that I can update the entries.

- [x] fork this repo
- [x] delete the book.org file
- [x] start converting the .md files (you can split them up however you find easiest)
- [ ] use graphviz to regenerate images (get the ground truth from the upstream `book.org`)
- [ ] localise the cover image using GIMP. The author field could read "by Sam Halliday, translated by **your name here**".
- [x] when you have a first chapter ready, I will create a book at http://leanpub.com/fpmortals-jp
- [ ] watch the upstream repository for bugfixes and new chapters (I am only planning one more chapter)
- [ ] use http://lulu.com to create physical prints from leanpub's "export" option.

I would request that the minimum price of the final book to be $0, but you can use what you want. I used $25 minimum when writing the book, and set it to $0 when I was finished.
you can create a custom cover too. I don't need any royalties.

**Comment by jkugiya** [comment]
Hi, I forked this repo and deleted book.org.

**Comment by jkugiya** [comment]
And I also translated first paragraph in `frontmatter.md`.

**Comment by jkugiya** [comment]
The original English sentence is left as a comment.

**Comment by fommil** [comment]
Excellent!

**Comment by jkugiya** [comment]
I translated `frontmatter.md`

**Comment by fommil** [comment]
Great! Please install the Hack font and customise the book cover in GIMP. Then let me know the book title, your email address, and I will create a leanpub page.

**Comment by jkugiya** [comment]
I modified cover.xcf by using gimp. Title is `Scalazによる関数型プログラミングへの道`.  I borrowed title from `Proposed Roads to Freedom` which is Russel's book. My email address is `j.kugiya@gmail.com`

**Comment by fommil** [comment]
@jkugiya please sign up for an account at leanpub.com and let me know your username

**Comment by fommil** [comment]
@jkugiya congratulations :tada: https://leanpub.com/fpmortals-jp :laughing:

**Comment by fommil** [comment]
btw you need to export the `cover.xcf` to `manuscript/images/title_page.png` for it to show up.

**Comment by jkugiya** [comment]
I replaced `manuscript/images/title_page.png`, just now.

**Comment by hepin1989** [comment]
@jkugiya I could learn from you:)

**Comment by fommil** [comment]
@jkugiya how is progress? :smile:

**Comment by jkugiya** [comment]
Maybe 20-30%.
I have been busy for a while, but I will restart soon.
