### ISSUE TITLE
discussion about implicit scope resolution

### ISSUE THREAD

**Issue by phderome** [fommil/fpmortals#23]
I just wonder if that is really essential to the book, considering it is very well treated elsewhere, quite lengthy and complex and whether typed FP developers really find the ability to have more than one evidence for a typeclass (compared to Haskell) to be a real benefit. The book will have a lot of material once completed, so maybe this is one area where there might be less coverage?

**Comment by fommil** [comment]
oooh yes, this is absolutely essential to the book. Implicits are used quite heavily in the typeclass approach as you'll find out in the next few chapters especially when I cover typeclass derivation :wink: I might cut the shapeless parts from that chapter though.

**Comment by fommil** [comment]
re-reading that section I agree it's a bit clunky though, so I'll definitely be addressing the readability in a follow up editing pass.
