### ISSUE TITLE
Polish Translation

### ISSUE THREAD

**Issue by fommil** [fommil/fpmortals#23]
Please comment here so that I can update the entries.

- [x] fork this repo
- [x] delete the book.org file
- [x] start converting the .md files (you can split them up however you find easiest)
- [ ] use graphviz to regenerate images (get the ground truth from the upstream `book.org`)
- [x] localise the cover image using GIMP. The author field could read "by Sam Halliday, translated by **your name here**".
- [x] when you have a first chapter ready, I will create a book at http://leanpub.com/fpmortals-pl
- [ ] watch the upstream repository for bugfixes and new chapters (I am only planning one more chapter)
- [ ] use http://lulu.com to create physical prints from leanpub's "export" option.

I would request that the minimum price of the final book to be $0, but you can use what you want. I used $25 minimum when writing the book, and set it to $0 when I was finished.
you can create a custom cover too. I don't need any royalties.

**Comment by szimano** [comment]
How does this work? Is someone working on this or is this for take?

**Comment by Krever** [comment]
Me, a bit :) Lets talk on gitter about details.

**Comment by Krever** [comment]
* Repo is forked: https://github.com/Krever/fpmortals-pl
* book.org deleted
* ~1.5k lines out of 15.5k translated, frontmatter, introduction and 2 chapters from `complete.md`
* Im not going to translate images, at least for now. I will asses if they can stay in English (as snippets do) at the end of translation.
* cover.xcf is translated, not sure about the remeaining png/svf files

**Comment by fommil** [comment]
Excellent! I'll try to find time to set this up this week.

you need to export the `cover.xcf` to `manuscript/images/title_page.png` for leanpub to pick up on it.

**Comment by Krever** [comment]
> you need to export the cover.xcf to manuscript/images/title_page.png for leanpub to pick up on it.
Makes sense. Done. Thx.

**Comment by fommil** [comment]
https://leanpub.com/fpmortals-pl should have something now, and @Krever you should have an email to add you as an author on leanpub.

**Comment by fommil** [comment]
errr, what is "Functional Programming for Mortals" in Polish? So I can update the title.

**Comment by fommil** [comment]
@Krever looks like you're missing this font, so the cover doesn't work so well (the hacker names should be `@fommil` with Hack font). https://sourcefoundry.org/hack/

**Comment by fommil** [comment]
this is pretty cool :laughing: 

https://leanpub.com/fpmortals-pl/read

Let me know when you want me to publicise it.

**Comment by Krever** [comment]
@fommil Awesome, thanks! I will update the cover soon.

**Comment by Krever** [comment]
Status:
* ~3k out of 15.3k lines translated (~20%)
* cover updated 
:)

**Comment by Krever** [comment]
Status: ~6k out of 16k lines translated (~38%) 

Work in progress, should hit halfway soon :)

**Comment by fommil** [comment]
this is awesome! Let me know when you're ready for a Tweet.

**Comment by Krever** [comment]
Now sounds good as it is 1/3 of a book ;)

**Comment by fommil** [comment]
ok, I'll do it in the morning... so all the Polish people are awake.

**Comment by fommil** [comment]
btw you can update the % complete status here https://leanpub.com/fpmortals-pl/edit_web_page_status

and consider filling out the Publish Checklist https://leanpub.com/fpmortals-pl/publish

**Comment by Krever** [comment]
Should be ok now, the publish checklist is all green. I allowed myself to translate about and teaser from the original, hope its ok. 
I see you have updated the complete status, thanks.

**Comment by Krever** [comment]
@fommil Out of curiosity: why have you chosen not to use syntax highlighting for code snippets?

**Comment by fommil** [comment]
@Krever it looks like a clown's face. Try it out for yourself and scream in horror.

**Comment by szimano** [comment]
https://imgflip.com/i/2lpb19

**Comment by fommil** [comment]
https://getyarn.io/yarn-clip/775ece63-7cee-462d-9a5b-7f724a930b84

**Comment by Krever** [comment]
Status: ~7.5k out of 16k lines translated (~47%)

Data types done, Advanced Monads on the way.

**Comment by Krever** [comment]
It took longer than expected, but Advanced Monads is complete. 
~70% of the book translated :)

**Comment by Krever** [comment]
Typeclass Derivation shipped. I'm a bit depressed after all the shapeless code read but besides that I'm good. I hope to finish the `complete.md` this weekend so only `backmatter,md` will be left.

Status: ~88% complete

**Comment by Krever** [comment]
And the `backmatter` is done as well. So now I will need a week or so to check upstream changes, download pdf and read it. After that, we can finally call it a day.

**Comment by fommil** [comment]
awesome stuff @Krever ! I will definitely tweet this out, and maybe we should contact some of the more popular Polish accounts to also popularise it. I don't expect there is any money to be made on this so perhaps we can find a sponsor who will get the book printed and distributed at conferences and other meetup events.

Have you been integrating my updates from `master`? There have been some fixes I've made in addition to yours.

**Comment by Krever** [comment]
Yes, the updates are incorporated now. Regarding the sponsor, IMHO it's a good idea, I will try to find some but I'm not very optimistic here, as I don't see any huge benefit for such a sponsor. I also tried to talk with `Helion`, which is a big polish technical books publisher, but they were not interested. 

Now I'm applying spell/grammar/stylistic fixes and hope to finish next week. Let's wait with announcements till then.

**Comment by Krever** [comment]
Also, @szimano owns a company, just saying...

**Comment by Krever** [comment]
@fommil Now it's complete. I don't plan to put any more work into this, unless someone finds and reports some improvements or bugs, so we can announce it. I already set the completeness to 100% on leanpub and you can set the price to 0$. 

I will reach out to some companies in regard to printing but I have little hope, so lets don't wait for that.

**Comment by fommil** [comment]
@Krever w00t! Congratulations! It's easy to set it up on leanpub if you want to buy a few copies for yourself and friends at cost price (typically $10 for paperback). I'll put out a tweet.

**Comment by szimano** [comment]
Status update, we will, most probably, print the book ;)

**Comment by fommil** [comment]
Awesome @szimano !
