### ISSUE TITLE
3.3 Stale.unapply why keys?

### ISSUE THREAD

**Issue by phderome** [fommil/fpmortals#24]
this code appears fine (though I am still checking) except for `(alive -- pending.keys)` since `alive` and `pending` are map so `.keys` appears to be unwanted. Is book's source code available publicly on github so I can verify such assumptions I may make before making a fool of myself (or pasting whatever is required in a REPL)?

```private object Stale {
    def unapply(world: WorldView): Option[NonEmptyList[MachineNode]] =
      world match {
        case WorldView(backlog, _, _, alive, pending, time) if alive.nonEmpty =>
          (alive -- pending.keys).collect {
            case (n, started)
                if backlog == 0 && timediff(started, time).toMinutes % 60 >= 58 =>
              n
            case (n, started) if timediff(started, time) >= 5.hours => n
          }.toList.toNel
  
        case _ => None
      }
  }```

**Comment by fommil** [comment]
Yeah there should be a link to the drone source code in the book. Grep for drone, it's on gitlab.

**Comment by phderome** [comment]
My ignorance.

**Comment by fommil** [comment]
Everything will eventually be rewritten to use scalaz data types. I guess there is a lesson, even in this, that more principled functionality is simpler to understand than a bunch of random methods on random classes.
