### ISSUE TITLE
Tight iteration

### ISSUE THREAD

**Issue by Krever** [fommil/fpmortals#25]
>There is tight iteration between writing the business logic and the algebra: it is a good level of abstraction to design a system.

I'm not sure if it's supposed to be `iteration` or `integration`.  If the former then its ok but I have no idea what that is supposed to mean :D If the latter then its better but still sounds a bit weird. as we are not integrating anything AFAIK. Maybe `connection` or `reflection`? Hard to say, but I find it hard to understand this sentence so maybe some rephrasal could be done anyway?

**Comment by fommil** [comment]
iteration in the sense of "understand the business problem, code it up, realise you didn't do it right, repeat" :smile:
