### ISSUE TITLE
comparing scalaz Foldable methods to stdlib (wording)

### ISSUE THREAD

**Issue by phderome** [fommil/fpmortals#25]
Remember that scalaz is a pure library of only total functions so index returns an Option, not an exception like .apply in the stdlib. **index is like .get,** indexOr is like .getOrElse and element is like .contains (requiring an Equal).

What I put in bold above should be removed IMHO, it seems confusing and possibly even inaccurate.

**Comment by fommil** [comment]
FYI I should be getting back to the swing of the book soon... I took a month to write `scalaz-deriving` and move house. I'll pick up your tickets before writing anything new. Thanks again!

**Comment by phderome** [comment]
verified to satisfaction.
