### ISSUE TITLE
In Scalaz presentation Traversable may warrant more explicit motivation

### ISSUE THREAD

**Issue by phderome** [fommil/fpmortals#26]
It may be a little difficult to follow without prior exposure of stdlib traverse or some fp lib usage of traverse. In my example of using traverse I try to traverse a list of stdlib of Futures but because Futures are impure the Future of the List cannot be assumed to be mapping the input List (a bug in th gist). IF Futures were to be replaced with Scalaz Task I assume order is preserved and we can just execute the Task at the end of transformation, which is nice. Developing an example like this could do well to motivate the Traversable definition.
https://gist.github.com/217cebbffd1773f12bada4eba7766080

This concept seems to be very important in FP community and is not developed much here when defined.

**Comment by fommil** [comment]
I don't want to take any digressions into the stdlib Future.traverse, but I can certainly look at adding more explanation here. Any discussion about parallelism is being delayed until the section on Advanced Monads.

**Comment by phderome** [comment]
It was more of an impression and commentary as I went along than anything else.

**Comment by fommil** [comment]
I wasn't aware that `Future.traverse` could rearrange the results... it is free to choose the execution order but if it is rearranging the results then it is broken more than I thought.
