### ISSUE TITLE
Suggestion for pronounciation

### ISSUE THREAD

**Issue by DaniRey** [fommil/fpmortals#3]
> A> `|+|` is known as the TIE Fighter operator. There is an Advanced TIE
A> Fighter in an upcoming section, which is very exciting.
A> Fighter in an upcoming section, which is very exciting.

I suggest that the TIE Fighter is pronounced "append". If you agree this could be.

> A> `|+|` is known as the TIE Fighter operator. There is an Advanced TIE
A> Fighter in an upcoming section, which is very exciting.
A> Fighter in an upcoming section, which is very exciting.
A> It is pronounced "append".

**Comment by fommil** [comment]
I think I mentioned already on Twitter... the convention is to actually call it the TIE Fighter :smile: 

Actually generally people like to make up silly names for the operators, and it's fun, and not something I'd want to take away from people. I seen a funny one just last week: `*>` "bird" and `<*` "flip the bird" :laughing:

**Comment by DaniRey** [comment]
"flipping the bird" is lovely.
All those fighters made me giggle as well. Great to see that the Scalaz community brings the fun to category theory.
