### ISSUE TITLE
Intro statement of Apply is tough to read to a novice

### ISSUE THREAD

**Issue by phderome** [fommil/fpmortals#32]
Original statement: Apply extends Functor by adding a method named ap which is similar to map in that it applies a function to values. However, with ap, the function is in a similar context to the values.

I understand the signature of def ap, I made a mental image of Functor as a List (to give myself a chance to see something) and imagine a ap that operated from one List to another as opposed from Int to Even numbers (A = Int, B = Even for example). I also see that technically your worded statement reflects accurately the Scala/FP/math definitions.

Nonetheless, it's hard to read and takes some time. I leave it to you to ponder whether I am normal, slow, it's the nature of the beast, or it could be worded to make it easier.

In fact ap is so similar to map (as your statement says) that it actually could be implemented by using it!!! Maybe that needs to be stated?

**Comment by fommil** [comment]
I agree it is tricky, but did you eventually understand it or is it still unclear?

**Comment by phderome** [comment]
I got it fine, though I don't know if I'd be typical reader. Author of Scalaz did have a point that he would not explain everything about relevant usage because people get a benefit from using their imagination without being spoon fed (just his bar might have been too high for me) and am sure that indeed happened for the first 100 versed users of the library. But 100 is a small number for a library that seems to deserve a broad audience.
