### ISSUE TITLE
`BigMachines ~> Machines`

### ISSUE THREAD

**Issue by Krever** [fommil/fpmortals#33]
>For example, in
>`drone-dynamic-agents` we may want to implement our Google Container Engine
>`Machines` algebra with an off-the-shelf algebra, `BigMachines`. Instead of
>changing all our business logic and tests to use this new `BigMachines`
>interface, we may be able to write a transformation from `Machines ~>
>BigMachines`.

Should it be `BigMachines ~> Machines` ?

**Comment by fommil** [comment]
I see what you mean, but I think it is correct as it is. There would be some mapping from the input algebra into the interpreter algebra, so given a message in `Machines[a]` you would be able to convert that into a `BigMachines[a]` and then interpret it. This comes up again later in the free monad section. I didn't actually implement it, so I'm guessing.

**Comment by Krever** [comment]
I see. So I will convert from `BigMachines` to `Machines` in (module) construction time and then the instance of `Machines` will be doing the conversion from `Machines` interface to `BigMachines` interface when called. Makes sense and probably both versions of phrasing this are correct.
