### ISSUE TITLE
ApplicativeBuilder tupled ill defined

### ISSUE THREAD

**Issue by phderome** [fommil/fpmortals#33]
Function f is applied without being declared or defined, where does it come from?

**Comment by fommil** [comment]
oh that looks like a typo. I have no idea how it got there. It is supposed to be `Tuple2.apply` not `f`

**Comment by fommil** [comment]
you could probably send a PR to `scalaz/scalaz` to fix that :wink: in `ApplicativeBuilder.scala`

```
  def tupled(implicit ap: Apply[M]): M[(A, B)] = apply(Tuple2.apply)
```

to

```
  def tupled(implicit ap: Apply[M]): M[(A, B)] = ap.tuple2(a, b)
```

**Comment by phderome** [comment]
I think the members of ApplicativeBuilder would read more easily as fa : F[A] and fb: F[B] rather than the current a, b (leaving a to denote an instance of A and b for B when required in other contexts). Another Scalaz notation issue that filtered here possibly?

**Comment by fommil** [comment]
Yeah I agree about the naming but I don't think it would be fair for me to rename the variables given how common it is the do this. I've already taken liberties to move implicit parameter to context bounds.

**Comment by phderome** [comment]
verified
