### ISSUE TITLE
Chinese Translation

### ISSUE THREAD

**Issue by hepin1989** [fommil/fpmortals#34]
Please comment here so that I can update the entries.

  - [x] fork this repo
  - [x] delete the book.org file
  - [x] start converting the .md files (you can split them up however you find easiest)
  - [ ] use graphviz to regenerate images (get the ground truth from the upstream book.org)
  - [ ] localise the cover image using GIMP. The author field could read "by Sam Halliday, translated by your name here".
  - [ ] when you have a first chapter ready, I will create a book at http://leanpub.com/fpmortals-cn
  - [ ] watch the upstream repository for bugfixes and new chapters (I am only planning one more chapter)
  - [ ] use http://lulu.com to create physical prints from leanpub's "export" option.

I would request that the minimum price of the final book to be $0, but you can use what you want. I used $25 minimum when writing the book, and set it to $0 when I was finished.
you can create a custom cover too. I don't need any royalties.

**Comment by fommil** [comment]
great!

**Comment by hepin1989** [comment]
First try，https://github.com/ReactivePlatform/fpmortals/blob/master/manuscript/frontmatter.md 
@fommil does everything of the book are there? Thanks, I think all the book contents are inside of the `complete.md` file.

**Comment by hepin1989** [comment]
Thank you for wrote this book, hope this book could be a first drug for scalaz:)

**Comment by hepin1989** [comment]
@fommil Could I add some translator comment to it? like this one below.

![image](https://user-images.githubusercontent.com/501740/49307284-a1a41600-f50f-11e8-8541-836fe07f91a4.png)

Which translate to : Translator view: Another nice functional programming library for Scala is [Cats](https://github.com/typelevel/cats), if intrested ,checkout on your own.

**Comment by fommil** [comment]
You can do what you want with the translation, but this book is not compatible with cats and readers will encounter serious problems if they attempt to use cats instead of scalaz.

**Comment by hepin1989** [comment]
Hm, seems like your words should be added to it, since it's a reminder from the original author:) thank you very much @fommil .

**Comment by fommil** [comment]
Personally I don't think it's relevant to discuss cats at all... much like we wouldn't mention that akka, or spring, can be used with this book.

**Comment by hepin1989** [comment]
Great！Thanks for your input, I will remove that to keep it clean. I will first try to keep both English and Chinese text and see what to do next.
