### ISSUE TITLE
Applicative mappy law overloads f

### ISSUE THREAD

**Issue by phderome** [fommil/fpmortals#36]
Fa is an ordinary member or value of F[A] whereas the second f is a function. There may be other clashes on f usage in the 5-6 laws in this area.

Using g for the function would help, though it seems like you're following standard usage and technically `fa` is to be understood as a single value not f applied to a (though funnily enough we see `ab` as a applied to b)

**Comment by fommil** [comment]
I don't see the typo here, can you please elaborate?

**Comment by phderome** [comment]
It's overloading of notation actually and it's probably so pervasive in community that no one notices it anymore:
```
map(fa)(f) === fa <*> pure(f)
```
`fa` in LHS is `F[a]` whereas `fa` in RHS is notation for `x=f(a)`, the value returned when `f` is applied to `a`. Those two usages of `fa` mean different things and yet they are used in the same equation to convey something.

**Comment by fommil** [comment]
I'll need to study this again when I have the brain cycles to spare.

**Comment by fommil** [comment]
I still don't see this... from the `scalaz.Applicative` law

```
 def mapLikeDerived[A, B](f: A => B, fa: F[A])(implicit FB: Equal[F[B]]): Boolean =
   FB.equal(map(fa)(f), ap(fa)(point(f)))
```
