### ISSUE TITLE
Some errors to fix

### ISSUE THREAD

**Issue by scf37** [fommil/fpmortals#42]
- DynAgents must be case class, otherwise `val program = DynAgents[Id]` won't compile
- Where should I import `Id`? shapeless.Id ?

**Comment by fommil** [comment]
the example project is available for you to view at https://gitlab.com/fommil/drone-dynamic-agents

I do not believe these are errors. Ping again here if you still see typos after looking at the source.

**Comment by fommil** [comment]
ah yes, the dynagents does look like a typo.

All imports are handled in the intro section: `import scalaz._, Scalaz._`

**Comment by fommil** [comment]
@scf37 download the book again, it's been fixed. Thanks for reporting the typo!
