### ISSUE TITLE
Confusing phrase in discussion of Int=>Boolean complexity

### ISSUE THREAD

**Issue by jpallas** [fommil/fpmortals#44]
I stumbled over

> `Int=>Boolean` is so big that if all implementations were assigned a unique number, each number would be 4GB.

Specifically, "each number would be 4GB" was confusing.  The "each number would be" phrasing suggested we were talking about the values rather than their representation.  Then the "4GB" confused me because it suggests bytes rather than bits.

Perhaps something like "each number would need 2^32 bits to represent it" would be less likely to lead the reader astray?

**Comment by fommil** [comment]
Thanks for your feedback, did you understand the text or is it still confusing you?

**Comment by jpallas** [comment]
If you think my alternative wording captures your intention, then I can't claim that I'm still confused.  But to arrive there, I had to tell myself that the text is inaccurate, because "4GB" reads as 2^32 bytes, not 2^32 bits.  (And I won't go near the "giga-" vs "gibi-" [SI prefix issue](https://physics.nist.gov/cuu/Units/binary.html).  Too many people just lose their minds over that.)

I'm trying to stay within the feedback rules of engagement.  The exact wording of the phrase is authorial discretion, but the difference between "GB" and "Gb" seems like a legitimate issue.  Avoiding the abbreviation entirely seemed like a good way to dodge the problem, but that's your call.

**Comment by fommil** [comment]
ok thanks, I'll say "gigabytes" instead of GB.

**Comment by fommil** [comment]
the book is updated. The "let's park it for now" thing is because I was getting a lot of FP wizards saying things like "I think you should talk about referential transparency and lambda calculus and the category theory before you talk about X"... and it was becoming a bit annoying. Small edits like this are perfectly valid feedback.
