### ISSUE TITLE
Georgian Translation

### ISSUE THREAD

**Issue by xxzefgh** [fommil/fpmortals#44]
Please comment here so that I can update the entries.
- [x] [fork this repo](https://github.com/xxzefgh/fpmortals-ka)
- [ ] delete the book.org file
- [ ] start converting the .md files (you can split them up however you find easiest)
- [ ] use graphviz to regenerate images (get the ground truth from the upstream `book.org`)
- [ ] localise the cover image using GIMP. The author field could read "by Sam Halliday, translated by **your name here**".
- [ ] when you have a first chapter ready, I will create a book at http://leanpub.com/fpmortals-pl
- [ ] watch the upstream repository for bugfixes and new chapters (I am only planning one more chapter)
- [ ] use http://lulu.com to create physical prints from leanpub's "export" option.

I would request that the minimum price of the final book to be $0, but you can use what you want. I used $25 minimum when writing the book, and set it to $0 when I was finished.
you can create a custom cover too. I don't need any royalties.

**Comment by fommil** [comment]
Excellent! We've had a very low success rate with translations. I'll follow through with a leanpub page when/if you reach 25%.
