### ISSUE TITLE
Defines future outside for in following example

### ISSUE THREAD

**Issue by dsysme** [fommil/fpmortals#45]
The following example form 2.2 Unhappy path defines future inside a for after stating that futures should be defined outside the for comprehension to run parallel. Maybe it doesn't matter in this case because first Future is a fail, but maybe its better to give examples that always adhere to the rules you suggest even if in this specific it doesn't matter. 
```
import scala.concurrent._
import ExecutionContext.Implicits.global
   for {  
           i <- Future.failed[Int](new Throwable)  
           j <- Future { println("hello") ; 1 }
         } yield (i + j) 
 Await.result(f, duration.Duration.Inf)
  caught java.lang.Throwable
```

**Comment by fommil** [comment]
Running futures in parallel is not always the goal.

**Comment by fommil** [comment]
I've re-read this text and I don't think there is an inconsistency here. As noted, "we will show a far superior way of defining parallel computations in a later chapter".

I'm going to close this ticket, thanks for your feedback.
