### ISSUE TITLE
More detail on avoiding cost of construction for implicit conversion

### ISSUE THREAD

**Issue by justinhj** [fommil/fpmortals#50]
# Suggestions

In section 4.2 I think it would be good to explain why the val is private and the AnyVal extension.

“implicit final class DoubleOps(private val x: Double) extends AnyVal ”

Also on that same page on the left there is repeated implementation of "implicit class DoubleOps" and I can't see any difference between them.

**Comment by fommil** [comment]
Hi thanks for your feedback. I will consider this when I am reviewing that chapter. If you have any more suggestions, please use the format requested in the template.

**Comment by justinhj** [comment]
I used the template but removed the irrelevant sections. I won't do that if I have future suggestions.

**Comment by fommil** [comment]
It's useful for me if you keep the sections so I can file it under the appropriate workflow. Thanks!

**Comment by justinhj** [comment]
I'm not sure the value classes thing is in Odersky's book because it came later, but you're probably right as it's easy enough to google for and not really FP related
