### ISSUE TITLE
Turn intercalate explenation on its head

### ISSUE THREAD

**Issue by DaniRey** [fommil/fpmortals#6]
Maybe start a new sub-chapter to talk about `intercalate`. And maybe even turn the explanation on its head. Starting with `mkString` and then moving to the generalized version called `intercalate`.

**Comment by fommil** [comment]
hmm, I'm not sure this would work. The structure is set up so that each typeclass gets a subsubsection and intercalate is just one of many functions on `Foldable`. I'm not against adding more headings for the Foldable, as it is quite long, if that's what you mean?

**Comment by DaniRey** [comment]
Yes, that's what I tried to say.
