### ISSUE TITLE
Explain the problem solved by Traverse

### ISSUE THREAD

**Issue by DaniRey** [fommil/fpmortals#8]
I assume that only readers who ever had to turn a List of Future into a Future of List, can immediately see how useful Traverse is. Maybe you can add an example to help the others.

> At the beginning of the chapter we showed the importance of `traverse`
and `sequence` for swapping around type constructors to fit a
requirement (e.g. `List[Future[_]]` to `Future[List[_]]`). You will
use these methods more than you could possibly imagine.

**Comment by fommil** [comment]
I am assuming this is a standard problem that comes up all the time for the typical scala dev... have you never needed to do this? Can you think of a more common one?

Honestly I've found `List[Future[...]] => Future[List[...]]` has come up more times than I can remember before I learnt FP.

**Comment by DaniRey** [comment]
I didn't have to do it for multiple years, but had to do it in two different projects just recently.

As I did not have to do it for quite some time, I assume some of your readers never came across this issue. I think referencing List[Future[...]] => Future[List[...]] makes sense in the text, but as an example I would use something simpler. What do you think about.

```
val input = IList("1", "3", "a")
input: scalaz.IList[String] = [1,3,a]
val parsed: IList[Try[Int]] = input.map(n => Try(Integer.parseInt(n)))
parsed: scalaz.IList[scala.util.Try[Int]] = [Success(1),Success(3),Failure(java.lang.NumberFormatException: For input string: "a")]
val numbers = ???
````

```
implicit def applicativeTry: Applicative[Try] = new Applicative[Try] {
  override def point[A](a: => A): Try[A] = Try(a)

  override def ap[A, B](fa: => Try[A])(f: => Try[(A) => B]): Try[B] = f.flatMap(fa.map)
}
val numbers = Traverse[IList].sequence(parsed)
```

My other idea was

```
final case class ExchangeRate(currency: String, rate: Double)

def toDollar: Maybe[ExchangeRate] = Just(ExchangeRate("Dollar", 0.5))
//def toYen: Maybe[ExchangeRate] = empty[ExchangeRate]
def toYen: Maybe[ExchangeRate] = Just(ExchangeRate("Yen", 1.0))

val exchangeRates: Maybe[NonEmptyList[ExchangeRate]] = Traverse[NonEmptyList].sequence(NonEmptyList(toDollar, toYen))
```
